import { Titanic } from "@titanic-entity/entity-resources";

Titanic.Localization.define("Titanic.UI.DataGrid", "en-US", {
  gridSettings: "Grid settings",
  configureColumns: "Registry setup",
  configureTotals: "Totals",
  rowActions: "Record actions",
  closeColumns: "Close",
  columnsTitle: "Registry setup",
  columnsCaption: "Configure visible columns for the registry.",
  listMode: "List",
  tileMode: "Tiles",
  totalsTitle: "Totals settings",
  totalsCaption: "Configure calculated totals for the registry.",
  totalsEmpty: "Totals settings are not configured yet.",
  visibleColumnsTitle: "Visible columns",
  availableColumnsTitle: "Column selection",
  searchColumnsPlaceholder: "Search by name or DB code",
  selectedColumnsSummary: "Displayed in the registry",
  availableColumnsSummary: "Available to add",
  addColumn: "Add",
  removeColumn: "Remove",
  moveColumn: "Move",
  moveColumnUp: "Move up",
  moveColumnDown: "Move down",
  columnWidth: "Width",
  columnSpan: "Span",
  columnLabel: "Label",
  columnTechnicalName: "Technical name",
  columnPropertiesTitle: "Column properties",
  columnPropertiesEmpty: "Select a column to configure it.",
  requiredColumn: "Required",
  renameColumn: "Rename",
  resetColumns: "Reset",
  saveColumns: "Save",
  cancelColumns: "Cancel",
  showColumn: "Show",
  hideColumn: "Hide",
  noAvailableColumns: "No columns found.",
  noSelectedColumns: "No displayed columns match the filter.",
  noColumnsToSaveWarning: "Add at least one field before saving the registry setup.",
  applyColumns: "Apply",
  saveDefaultColumns: "Set as default",
  savingColumns: "Saving...",
  columnSettingsLoadError: "Failed to load column settings",
  columnSettingsSaveError: "Failed to save column settings",
  loading: "Loading...",
  loadingMore: "Loading more records...",
  loadingStructure: "Loading columns...",
  empty: "No records",
  error: "Failed to load data",
  openRecord: "Open",
  saveRecord: "Save",
  cancelRecord: "Cancel",
  deleteRecord: "Delete",
  copyRecord: "Copy",
  sortColumns: "Sort",
  sortAscending: "ascending",
  sortDescending: "descending",
  booleanTrue: "Yes",
  booleanFalse: "No",
  selectRow: "Select row",
  selectAllRows: "Select all rows",
  cancelSelection: "Cancel multi-select"
}, { defaultLocale: "ru-RU" });
