import { Titanic } from "@titanic-entity/entity-resources";

Titanic.Localization.define("Titanic.UI.DataGrid", "ru-RU", {
  gridSettings: "Настройки реестра",
  configureColumns: "Настройка реестра",
  configureTotals: "Итоги",
  rowActions: "Действия записи",
  closeColumns: "Закрыть",
  columnsTitle: "Настройка реестра",
  columnsCaption: "Настройте набор колонок реестра.",
  listMode: "Список",
  tileMode: "Плитка",
  totalsTitle: "Настройки итогов",
  totalsCaption: "Настройте расчет итогов для реестра.",
  totalsEmpty: "Итоги для этого реестра пока не настроены.",
  visibleColumnsTitle: "Видимые колонки",
  availableColumnsTitle: "Выбор колонки",
  searchColumnsPlaceholder: "Поиск по названию или коду",
  selectedColumnsSummary: "Отображаются в реестре",
  availableColumnsSummary: "Можно добавить",
  addColumn: "Добавить",
  removeColumn: "Убрать",
  moveColumn: "Переместить",
  moveColumnUp: "Переместить вверх",
  moveColumnDown: "Переместить вниз",
  columnWidth: "Ширина",
  columnSpan: "Ячеек",
  columnLabel: "Подпись",
  columnTechnicalName: "Техническое имя",
  columnPropertiesTitle: "Свойства колонки",
  columnPropertiesEmpty: "Выберите колонку для настройки.",
  requiredColumn: "Обязательно",
  renameColumn: "Переименовать",
  resetColumns: "Сбросить",
  saveColumns: "Сохранить",
  cancelColumns: "Отмена",
  showColumn: "Показать",
  hideColumn: "Скрыть",
  noAvailableColumns: "Подходящие колонки не найдены.",
  noSelectedColumns: "Нет отображаемых колонок по текущему фильтру.",
  noColumnsToSaveWarning: "Не добавлено ни одного поля. Добавьте поле перед сохранением.",
  applyColumns: "Применить",
  saveDefaultColumns: "Установить по умолчанию",
  savingColumns: "Сохранение...",
  columnSettingsLoadError: "Не удалось загрузить настройки колонок",
  columnSettingsSaveError: "Не удалось сохранить настройки колонок",
  loading: "Загрузка...",
  loadingMore: "Загрузка следующих записей...",
  loadingStructure: "Загрузка колонок...",
  empty: "Нет записей",
  error: "Не удалось загрузить данные",
  openRecord: "Открыть",
  saveRecord: "Сохранить",
  cancelRecord: "Отмена",
  deleteRecord: "Удалить",
  copyRecord: "Копировать",
  sortColumns: "Сортировка",
  sortAscending: "по возрастанию",
  sortDescending: "по убыванию",
  booleanTrue: "Да",
  booleanFalse: "Нет",
  selectRow: "Выбрать строку",
  selectAllRows: "Выбрать все строки",
  cancelSelection: "Отменить множественный выбор"
}, { defaultLocale: "ru-RU" });
